config/routes.rb
Dd::Application.routes.draw do

  
  resources :password_resets
  resources :skills
  resources :users
  resources :session, only: [:new, :create, :destroy]
  resources :dashboard
  resources :settings
  resources :employees do
    collection { post :import }
  end
  resources :calls do
    collection { post :import }
  end
  resources "contacts", only: [:new, :create]
  resources "requests", only: [:new, :create]

    root 'session#new'
    get 'signin', to: "session#new"
    match 'signout', to: "session#destroy", via: :delete
    get 'administration', to: "admin_users#index", as: "administration"
    get 'employee_import', to: "employees#employee_import"
    get 'employee_active', to: "employees#active"
    get 'employee_leave', to: "employees#leave"
    get 'employee_sick', to: "employees#sick"
    get 'employee_maternity', to: "employees#maternity"
    get 'employee_compassionate', to: "employees#compassionate"
    get 'employee_retrenched', to: "employees#retrenched"
    get 'employee_active_allocate', to: "employees#active_allocate"
    match '/contacts', to: 'contacts#new', via: 'get'
    match '/requests', to: 'requests#new', via: 'get'
    get "active/new"
    

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	def index
		if signed_in? && current_user.role_id == 2
			@users = User.all
			@active_employees = Employee.where(:user_id => current_user.id).count
			@graph_data = monthly_calls
			
			gon.graph_data = @graph_data
			gon.graph_mti = graph_monthly_traffic_intensity

			gon.graph_success = graph_call_success
			gon.graph_unsuccessful = graph_call_unsuccessful
		else
			flash[:error] = "Need to be signed in!"
			redirect_to signin_path
		end	
	end
end

app/helpers/dashboard_helper.rb
module DashboardHelper

	## String representing active employees vs total employees
	def active_employees_display		
		current_user_active_employees_count.to_s + "/" + current_user_employees_count.to_s
	end

	## Capacity Usage percantage
	def active_employees_handle_check
		((current_user_active_employees_count.to_f / current_user_employees_count.to_f)*100).floor.to_s + "% of Capacity "
	end

end

app/views/dashboard/index.html.erb
<!--=====================================================
  Dashboard Quick Stats
===================================================== -->
<div class="row">
  <section class="twelve columns container">  
  <header class="main-page-header">
    Dashboard 
  </header>
  <p>Welcome to your dashboard. View all data relevant to your call centre.</p> 

  <table class="statistics-table">
    <thead>
      <th width="25%">Active Employees</th>
      <th width="25%">Avg Daily Call Load</th>
      <th width="25%">Service Level</th>
      <th width="25%">Capacity</th>
    </thead>
    <tr class="values">
      <td><%= active_employees_display %></td>
      <td><%= calls_per_day %></td>
      <td><%= current_service_level %>%</td>
      <td><%= capa.round(1) %></td>
    </tr>
    <tr class="comparison">
      <td><%= link_to "View Employees", employees_path %></td>
      <td>No Messages</td>
      <td><%= link_to "View Log", calls_path %></td>
      <td>With RSL = <%= current_user.settings.service_level %>%</td>
    </tr>
  </table>

  <div>
  
  </div>

  </section>
</div>


<!--=====================================================
  Dashboard Charts
===================================================== -->
<div class="row">
  <div class="six columns container charting">
    <header class="main-page-header">
      Monthly Call Numbers &amp; Traffic Intensity ( <%= current_year %> ) 
      <p class="chart-description">total calls in each month with corresponding intensity</p>
    </header>

    <div class="legend">
      <ul>
        <li>Calls</li>
        <li>Traffic Intensity</li>
      </ul>
    </div>
    <div id="chart-container">
      <canvas id="call-intensity-chart" width="300" height="200"></canvas>
    </div>
  </div>

  <div class="six columns container charting">
    <header class="main-page-header">
      Call Success Chart ( <%= current_year %> )
      <p class="chart-description">successful vs unsuccessful calls</p>
    </header>
    <div class="legend">
      <ul>
        <li>Successful</li>
        <li>Unsuccessful</li>
      </ul>
    </div>
    <div id="chart-container">
      <canvas id="call-success-chart" width="300" height="200"></canvas>
    </div>
  </div>
</div>

<!--=====================================================
  Dashboard Reports
===================================================== -->
<div class="row">
  <div class="twelve columns container">
    <header class="main-page-header">
      Call Centre Reports 
    </header>

    <table class="general-table">
      <tr>
        <td width="20%"><strong>Current Service Level</strong></td>
        <td width="20%"><%= current_service_level %>%</td>
        <td width="60%">
          Expected Service level is <%= current_user.settings.service_level %>
          
        </td>
      </tr>
      <tr>
        <td width="20%"><strong>Average Call Wait Time</strong></td>
        <td width="20%"><%= avg_call_wait/60 %> min </td>
        <td width="60%">
          This is <%= ((avg_call_wait)-current_user.settings.target_answer_time) %>secs longer than the target answer time. 
          This should be addressed.
        </td>
      </tr>
     


    </table>
    
  </div>
</div>