config/routes.rb
Dd::Application.routes.draw do

  
  resources :password_resets
  resources :skills
  resources :users
  resources :session, only: [:new, :create, :destroy]
  resources :dashboard
  resources :settings
  resources :employees do
    collection { post :import }
  end
  resources :calls do
    collection { post :import }
  end
  resources "contacts", only: [:new, :create]
  resources "requests", only: [:new, :create]

    root 'session#new'
    get 'signin', to: "session#new"
    match 'signout', to: "session#destroy", via: :delete
    get 'administration', to: "admin_users#index", as: "administration"
    get 'employee_import', to: "employees#employee_import"
    get 'employee_active', to: "employees#active"
    get 'employee_leave', to: "employees#leave"
    get 'employee_sick', to: "employees#sick"
    get 'employee_maternity', to: "employees#maternity"
    get 'employee_compassionate', to: "employees#compassionate"
    get 'employee_retrenched', to: "employees#retrenched"
    get 'employee_active_allocate', to: "employees#active_allocate"
    match '/contacts', to: 'contacts#new', via: 'get'
    match '/requests', to: 'requests#new', via: 'get'
    get "active/new"
    

end

app/models/employee.rb
class Employee < ActiveRecord::Base
	require 'csv'
	include SessionHelper

	scope :active, -> { where("employee_status_id = ?", 1) }

	#Associations
	belongs_to :user
	has_many :skills
	has_many :calls
	has_one :employee_status
	#accepts_nested_attributes_for :user

	#CallBacks - Things to be done before object is saved to database
	before_save { |employee| employee.employee_email = employee_email.downcase }
	#before_create :set_status

	#REGEX for correct email format
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	VALID_NAME_REGEX =  /\A[a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*$/

	HUMANIZED_ATTRIBUTES = {
		:employee_fname => "First Name",
		:employee_lname => "Last Name",
		:employee_email => "Email Address",
		:employee_contact_num => "Contact Number",
	}

	#Validations
	validates :employee_fname, :presence => true, length: { maximum:25 }, format: { with: VALID_NAME_REGEX, :multiline => true }
	validates :employee_lname, :presence => true, length: { maximum:25 }, format: { with: VALID_NAME_REGEX, :multiline => true }
	validates :employee_email, :presence => true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	validates :employee_contact_num, :presence => true, length: { minimum: 10, maximum:10 }
	validates :employee_started, :presence => true
	validates_numericality_of :employee_contact_num

	#Get Employee full name, for display purposes
	def full_name
		self.employee_fname.capitalize + " " + self.employee_lname.capitalize
	end

	def full_name_rev
		self.employee_lname.capitalize + ", " + self.employee_fname.capitalize
	end

	def set_status
		self.employee_status_id = 1
	end

	def set_owner
		self.user_id = current_user.id
	end

	def self.import(file, user_id)
		CSV.foreach(file.path, headers: true) do |row|
			e = Employee.new row.to_hash.merge(user_id: user_id)
			e.set_status
			e.save!
		end
	end

	def self.search(query)
	  where("employee_lname || employee_fname like ?", "%#{query}%")
	end

	def self.human_attribute_name(attr, options={})
		HUMANIZED_ATTRIBUTES[attr.to_sym] || super
	end
	
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  include SessionHelper
  #include ApplicationHelper

  # GET /employees
  # GET /employees.json
  def index
    if signed_in? && current_user.role_id == 2

      # Search Results
      if params[:search]
        search_query = params[:search]
        #@employees = all_employees.search(params[:search]).sort { |a,b| a.employee_lname <=> b.employee_lname }
        @employees = all_employees.search(params[:search]).sort { |a,b|
            [a.employee_status_id, a.employee_lname ]<=>
            [b.employee_status_id, b.employee_lname]
          }.paginate(:page => params[:page], :per_page => 15)
      else
        @employees = all_employees.sort { |a,b|
            [a.employee_status_id, a.employee_lname ]<=>
            [b.employee_status_id, b.employee_lname]
          }.paginate(:page => params[:page], :per_page => 15)
      end
    else
      restricted_access
    end


  end



  def active
    if signed_in? && current_user.role_id == 2

      # Search Results
      @employees=[]
        all_employees.each do|e|
            if (e.employee_status_id == 1)
                @employees << e
            end
    end
    else
        flash[:error] = "You don't have any actives employee at the moment"
        redirect_to employees_path
      end
  end



    def active_allocate
        if signed_in? && current_user.role_id == 2

            # Search Results
            @employees=[]
                all_employees.each do|e|
                    if (e.employee_status_id == 1)
                        @employees << e
                    end
            end
        else
            flash[:error] = "You don't have any actives employee at the moment"
            redirect_to employees_path
        end
    end



     def leave
    if signed_in? && current_user.role_id == 2

      # Search Results
      @employees=[]
        all_employees.each do|e|
            if (e.employee_status_id == 2)
                @employees << e
            end
            end
    else
        flash[:error] = "There are no employee on leave at the moment"
        redirect_to employees_path
      end
    end

    def maternity
    if signed_in? && current_user.role_id == 2

      # Search Results
      @employees=[]
        all_employees.each do|e|
            if (e.employee_status_id == 3)
                @employees << e
            end
            end
    else
        flash[:error] = "There are no employee on leave at the moment"
        redirect_to employees_path
      end
    end

   def sick
    if signed_in? && current_user.role_id == 2

      # Search Results
      @employees=[]
        all_employees.each do|e|
            if (e.employee_status_id == 4)
                @employees << e
            end
            end
    else
        flash[:error] = "There are no employee on leave at the moment"
        redirect_to employees_path
      end
    end

     def compassionate
    if signed_in? && current_user.role_id == 2

      # Search Results
      @employees=[]
        all_employees.each do|e|
            if (e.employee_status_id == 5)
                @employees << e
            end
            end
    else
        flash[:error] = "There are no employee on leave at the moment"
        redirect_to employees_path
      end
    end


   def retrenched
    if signed_in? && current_user.role_id == 2

      # Search Results
      @employees=[]
        all_employees.each do|e|
            if (e.employee_status_id == 6)
                @employees << e
            end
            end
    else
        flash[:error] = "There are no employee on leave at the moment"
        redirect_to employees_path
      end
    end
  # GET /employees/1
  # GET /employees/1.json
  def show
    if signed_in? && current_user.role_id == 2 && set_employee.user_id == current_user.id
      # Get appropriate Employee
      @employee = Employee.find(params[:id])
      # Get Employee's religion
      @religion = Religion.where(:id => @employee.religion_id).first.religion_name.capitalize
    else
      flash[:error] = "You don't have an employee with that ID"
      redirect_to employees_path
    end
  end

  def import
    if signed_in? && current_user.role_id == 2
      initial_count = all_employees.count
      begin
        Employee.import(params[:file], current_user.id)
        num_records = all_employees.count - initial_count
        flash[:success] = "#{num_records} employees imported successfully"
        redirect_to employees_path
      rescue ActiveRecord::RecordInvalid
        flash[:error] = "Invalid CSV File"
        redirect_to employee_import_path
      end


    else
      restricted_access
    end
  end

  def search
    @employee = Employee.search(params[:search])
  end

  # GET /employees/new
  def new
    if signed_in? && current_user.role_id == 2
      @employee = Employee.new
      @religions = Religion.all
      @current_user_id = current_user.id
    else
      restricted_access
    end
  end

  # GET /employees/1/edit
  def edit
    if signed_in? && current_user.role_id == 2 && set_employee.user_id == current_user.id
      @religions = Religion.all
    else
      flash[:error] = "You don't have an emplyee with that ID"
      redirect_to employees_path
    end
  end

  # POST /employees
  # POST /employees.json
  def create
    if signed_in? && current_user.role_id == 2
      @employee = Employee.new(employee_params)
      @religions = Religion.all

      respond_to do |format|
        if @employee.save
          emp_name = @employee.full_name
          format.html { redirect_to @employee, notice: emp_name + ' was successfully created.' }
          format.json { render action: 'show', status: :created, location: @employee }
        else
          format.html { render action: 'new' }
          format.json { render json: @employee.errors, status: :unprocessable_entity }
        end
      end
    else
      restricted_access
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    @religions = Religion.all
    if signed_in? && current_user.role_id == 2 && set_employee.user_id == current_user.id
      respond_to do |format|
        if @employee.update(employee_params)
          format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @employee.errors, status: :unprocessable_entity }
        end
      end
    else
      restricted_access
    end
  end


  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:employee_fname, :employee_lname,:employee_left, :employee_started, :employee_contact_num, :employee_status_id, :employee_email, :religion_id, :user_id)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
	def employee_religion(id)
		Religion.where(:id => id).first.religion_name.capitalize
	end

	## This method calculates the performance values for a specific employee
	def employee_performance(employee)
		#Check if there is any call data associated with this employee
		if all_calls.where(:employee_id => employee.id).any?

			## Array holding all calls handled by this employee
			calls_by_this_employee = all_calls.where("employee_id =?", employee.id)

	    ## Calls report for this employee
	    @calls_report = call_sorter(calls_by_this_employee.limit(100))

			## Total number of calls handled by this employee
	    @call_count = calls_by_this_employee.count

	    ## Number of successful calls (call_status_id = 1)
	    @success_calls = calls_by_this_employee.where("call_status_id = ?", 1).count

	    ## Percentage of succesful calls
	    @success_percentage = ((@success_calls.to_f/@call_count.to_f)*100).floor
	      
	    ## Calls Per Day
	    @calls_per_day = (@call_count.to_f/total_num_days).floor

    	## Average Call duration
      @average_call_duration = ((calls_by_this_employee.sum("call_duration")/60)/@call_count).to_s + "mins"
	  else
	  	## Defaults
	  	@calls_report = []
	  	@call_count = "None Recorded"
	  	@success_calls = 0
	  	@success_percentage = 0
	  	@calls_per_day = "None Recorded"
	  	@average_call_duration = "0mins"
  	end 
	end

	## List containing current user's employees
	def current_user_employees
		@cue = current_user.employees
	end

	## The Current User's Total Active Employee Count
	def current_user_active_employees_count
		@cueac = current_user_employees.active.count
	end

	## The Current User's Total Employee count
	def current_user_employees_count
		@cuec = current_user_employees.count
	end


	def convert_to_mins(secs)
		secs / 60
	end

	#==================================================================
	##	Comparisons
	#==================================================================

	def employee_call_count_comparison(employee)
		if employee.calls.any?
			## Total number of Calls
			call_count = all_calls.count
			## Total number of calls handled by this employee
			curr_employee_call_count = all_calls.where(:employee_id => employee.id).count
			## Total number of employees
			employee_count = all_employees.count
			## Average expected call count/per employee
			avg = (call_count/employee_count).to_f
			## Difference between expected call count and current employee count
			diff = avg - curr_employee_call_count
			
			if diff > 0
				((diff/avg)*100).round(1).to_s + "% LT Avg " + "( " + avg.to_s + " )"
			elsif diff < 0
				(((diff*-1)/avg*100)).round(1).to_s + "% HT Avg " + "( " + avg.to_s + " )"
			else
				"= Avg " + "( " + avg.to_s + " )"
			end	
		else
			0
		end
	end

	def employee_success_comparison(employee)
		if employee.calls.any?
			emp_total_calls = all_calls.where(employee_id: employee.id)
			emp_total_calls_count = all_calls.where(employee_id: employee.id).count
			emp_success_calls = emp_total_calls.where(call_status_id: 1).count

			emp_success_percentage = ((emp_success_calls.to_f/emp_total_calls_count.to_f)*100).floor

			diff = success_percentage - emp_success_percentage
			diff_percentage = (success_percentage.to_f * (diff.to_f/100)).round(1)

			
			if diff_percentage > 0
				(diff_percentage).to_s + "% LT Avg " + "( " + success_percentage.to_s + "% )"
			elsif diff_percentage < 0
				(diff_percentage*-1).to_s + "% HT Avg " + "( " + success_percentage.to_s + "% )"
			else
				"= Avg " + "( " + success_percentage.to_s + "% )"
			end	
		else
			0
		end
	end

	def employee_avg_calls_comparison(employee)
		if employee.calls.any?
			emp_total_calls = all_calls.where(employee_id: employee.id).count
			emp_calls_per_day = (emp_total_calls.to_f/total_num_days.to_f)

			avg_calls_per_day_per_employee = ((all_calls.count / total_num_days)/all_employees.count).round(1)

			diff = (avg_calls_per_day_per_employee - emp_calls_per_day).round(1)

			percent_diff = ((diff / avg_calls_per_day_per_employee)*100).round(1)

			if percent_diff < 0
				(percent_diff*-1).to_s + "% HT Avg " + "( " + avg_calls_per_day_per_employee.to_s + " )"
			elsif percent_diff > 0
				percent_diff.to_s + "% LT Avg " + "( " + avg_calls_per_day_per_employee.to_s + " )"
			else
				"= Avg " + "( " + avg_calls_per_day_per_employee.to_s + " )"
			end	
		else
			0
		end
	end

	def employee_avg_time_comparison(employee)
		if employee.calls.any?
			employee_avg_duration = (all_calls.where(employee_id: employee.id).average(:call_duration)/60).round(1)
			diff = avg_call_duration - employee_avg_duration

			percent_diff = ((diff/avg_call_duration)*100).round(1)

			if percent_diff < 0
				(percent_diff*-1).to_s + "% HT Avg " + "( " + avg_call_duration.to_s + " )" 
			elsif percent_diff > 0
				percent_diff.to_s + "% LT Avg " + "( " + avg_call_duration.to_s + " )" 
			else
				"= Avg " + "( " + avg_call_duration.to_s + " )" 
			end
		else
			0
		end
	end
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <ul class="basic-form">
    <li>
      <%= f.label "First Name" %>
      <%= f.text_field :employee_fname, :required => true, :class => "input" %>
    </li>

    <li>
      <%= f.label "Last Name" %>
      <%= f.text_field :employee_lname, :required => true, :class => "input" %>
    </li>

    <li><%= f.label "Employment Commencement" %>
      <%= f.date_select :employee_started, :required => true, :class => "input" %>
    </li>

    <li><%= f.label "Contact Number" %>
      <%= f.text_field :employee_contact_num, :required => true, :required => true, :class => "input" %>
    </li>

    <li><%= f.label "Email Address" %>
      <%= f.text_field :employee_email, :required => true, :class => "input" %>
    </li>

     <li><%= f.label "Religion" %><br>
     <select name="employee[religion_id]">
      <% @religions.each do |religion| %>
        <option value = <%= religion.id %> ><%= religion.religion_name.capitalize %></option>
      <% end %>
     </select>
    </li>
  </ul>

  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :employee_status_id, :value => 1 %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/active.html.erb
<section  class="twelve columns container">

<header class="main-page-header">Active Employees ( <%= current_user_employees.where(:employee_status_id => 1).count %> )
<span class="import-button"><%= link_to "Allocate Employees", employee_active_allocate_path %></span>
</header>

<table class="general-table">
  <thead>
    <tr>
      <th>Employee Id</th>
      <th>Full Name</th>
      <th>Commenced Work</th>
      <th>Contact Number</th>
      <th>Email Address</th>
      <th>Current Status</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td>DD_<%= employee.id %></td>
        <td><%= link_to employee.full_name_rev.upcase, employee, :class => "employee-name" %></td>
        <td><%= employee.employee_started %></td>
        <td><%= employee.employee_contact_num %></td>
        <td><%= employee.employee_email %></td>
        <td><%= EmployeeStatus.find(employee.employee_status_id).es_type.capitalize %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</section>

app/views/employees/active_allocate.html.erb
<section  class="twelve columns container">


<%= form_for(:employee_status_id, method: "@employees.update") do |f| %>

<header class="main-page-header">Active Employees ( <%= current_user_employees.where(:employee_status_id => 1).count %> )
<span class="import-button"><%= link_to "Cancel Allocations", employee_active_path %></span>
<%= f.submit %>
<% end %>
</header>

<table class="general-table">
  <thead>
    <tr>
      <th>Employee Id</th>
      <th>Full Name</th>
      <th>Commenced Work</th>
      <th>Contact Number</th>
      <th>Email Address</th>
      <th>Current Status</th>
    </tr>
  </thead>

  <tbody>
      <% @employees.each do |employee| %>
      <tr>
        <td>DD_<%= employee.id %></td>
        <td><%= link_to employee.full_name_rev.upcase, employee, :class => "employee-name" %></td>
        <td><%= employee.employee_started %></td>
        <td><%= employee.employee_contact_num %></td>
        <td><%= employee.employee_email %></td>
        <td><%=  select("es", "select",  options_for_select([EmployeeStatus.find(employee.employee_status_id + 1).es_type] +
            EmployeeStatus.all.map{ |s| [s.es_type, s.id]}), :prompt => 'Select New Status')%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</section>

app/views/employees/compassionate.html.erb
<section  class="twelve columns container">

<header class="main-page-header">Employees On Compassionate Leave ( <%= current_user_employees.where(:employee_status_id => 5).count %> )
<span class="import-button"><%= link_to "Allocate", new_employee_path %></span>
</header>

<table class="general-table">
  <thead>
    <tr>
      <th>Employee Id</th>
      <th>Full Name</th>
      <th>Commenced Work</th>
      <th>Contact Number</th>
      <th>Email Address</th>
      <th>Current Status</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td>DD_<%= employee.id %></td>
        <td><%= link_to employee.full_name_rev.upcase, employee, :class => "employee-name" %></td>
        <td><%= employee.employee_started %></td>
        <td><%= employee.employee_contact_num %></td>
        <td><%= employee.employee_email %></td>
        <td><%= EmployeeStatus.find(employee.employee_status_id).es_type.capitalize %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</section>

app/views/employees/edit.html.erb
<section  class="twelve columns container">
	<header class="main-page-header">Edit <%= @employee.full_name %></header>
	<%= render 'form' %>
	<%= link_to 'Show', @employee %> |
	<%= link_to 'Back', employees_path %>
</section>

app/views/employees/employee_import.html.erb
<section  class="twelve columns container">
<header class="main-page-header">Import Employees</header>

<div class="csv-import">
	<h3>Import a <strong>CSV</strong> File</h3>
	<%= form_tag import_employees_path, multipart: true do %>
	<%= file_field_tag :file %>
	<%= hidden_field :user_id, :value => current_user.id.to_i %>
	<%= submit_tag "Import CSV" %>
	<% end %>
</div><!-- CSV Import -->



</section>

app/views/employees/index.html.erb
<section  class="twelve columns container">

<header class="main-page-header">All Employees ( <%= current_user_employees_count %> )
  <span class="import-button"><%= link_to "Add New", new_employee_path %></span>
</header>

<table class="general-table">
  <thead>
    <tr>
      <th>Employee Id</th>
      <th>Full Name</th>
      <th>Commenced Work</th>
      <th>Contact Number</th>
      <th>Email Address</th>
      <th>Current Status</th>
      <th>Change Status</th>
      <th>Save Status</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td>DD_<%= employee.id %></td>
        <td><%= link_to employee.full_name_rev.upcase, employee, :class => "employee-name" %></td>
        <td><%= employee.employee_started %></td>
        <td><%= employee.employee_contact_num %></td>
        <td><%= employee.employee_email %></td>
        <td><%= EmployeeStatus.find(employee.employee_status_id).es_type.capitalize %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @employees %>
</section>

app/views/employees/leave.html.erb
<section  class="twelve columns container">

<header class="main-page-header">Employees on Company Leave ( <%= current_user_employees.where(:employee_status_id => 2).count %> )
<span class="import-button"><%= link_to "Allocate", new_employee_path %></span>
</header>

<table class="general-table">
  <thead>
    <tr>
      <th>Employee Id</th>
      <th>Full Name</th>
      <th>Commenced Work</th>
      <th>Contact Number</th>
      <th>Email Address</th>
      <th>Current Status</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td>DD_<%= employee.id %></td>
        <td><%= link_to employee.full_name_rev.upcase, employee, :class => "employee-name" %></td>
        <td><%= employee.employee_started %></td>
        <td><%= employee.employee_contact_num %></td>
        <td><%= employee.employee_email %></td>
        <td><%= EmployeeStatus.find(employee.employee_status_id).es_type.capitalize %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</section>

app/views/employees/maternity.html.erb
<section  class="twelve columns container">

<header class="main-page-header">Employees on Maternity Leave ( <%= current_user_employees.where(:employee_status_id => 3).count %> )
<span class="import-button"><%= link_to "Allocate", new_employee_path %></span>
</header>

<table class="general-table">
  <thead>
    <tr>
      <th>Employee Id</th>
      <th>Full Name</th>
      <th>Commenced Work</th>
      <th>Contact Number</th>
      <th>Email Address</th>
      <th>Current Status</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td>DD_<%= employee.id %></td>
        <td><%= link_to employee.full_name_rev.upcase, employee, :class => "employee-name" %></td>
        <td><%= employee.employee_started %></td>
        <td><%= employee.employee_contact_num %></td>
        <td><%= employee.employee_email %></td>
        <td><%= EmployeeStatus.find(employee.employee_status_id).es_type.capitalize %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</section>

app/views/employees/new.html.erb
<section  class="twelve columns container">
<header class="main-page-header">Create New Employee</header>

<%= render 'form' %>


</section>

app/views/employees/retrenched.html.erb
<section  class="twelve columns container">

<header class="main-page-header">Employees who have been FIRED ( <%= current_user_employees.where(:employee_status_id => 6).count %> )
<span class="import-button"><%= link_to "Allocate", new_employee_path %></span>
</header>

<table class="general-table">
  <thead>
    <tr>
      <th>Employee Id</th>
      <th>Full Name</th>
      <th>Commenced Work</th>
      <th>Contact Number</th>
      <th>Email Address</th>
      <th>Current Status</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td>DD_<%= employee.id %></td>
        <td><%= link_to employee.full_name_rev.upcase, employee, :class => "employee-name" %></td>
        <td><%= employee.employee_started %></td>
        <td><%= employee.employee_contact_num %></td>
        <td><%= employee.employee_email %></td>
        <td><%= EmployeeStatus.find(employee.employee_status_id).es_type.capitalize %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</section>

app/views/employees/show.html.erb
<div class="row">
<section  class="twelve columns container">
 
  <header class="main-page-header">
    <%= @employee.full_name %>
    <span class="import-button"><%= link_to "Edit", edit_employee_path(@employee) %></span>
  </header>

  <div id="employee-details">
    <table class="general-table">
      <thead>
        <th width="25%">Email</th>
        <th width="25%">Contact Number</th>
        <th width="25%">Started Work</th>
        <th width="25%">Current Status</th>
      </thead>
      <tbody>
      <tr>
        <td><a href="mailto:<%= @employee.employee_email %>" title="Send E-mail to <%= @employee.full_name %>">
          <%= @employee.employee_email %></a></td>
        <td><%= @employee.employee_contact_num %></td>
        <td><%= @employee.employee_started %></td>
        <td><%= EmployeeStatus.find(@employee.employee_status_id).es_type.capitalize %></td>
      </tr>
      </tbody>
    </table> 
  </div><!-- Employee Details -->
</section>
</div>

<div class="row">
  <section id="employee-performance" class="twelve columns container">
    <header class="emp-performance-header">
      Performance
    </header>

    <div class="performance-legend">
      <strong>Terms:</strong> <strong>LT</strong> = Lower Than, <strong>HT</strong> = Higher Than, <strong>Avg</strong> = Average
    </div>

    <table class="statistics-table">
      <thead>
        <th>Total Calls Handled</th>
        <th>Success Rate</th>
        <th>Avg Calls / Day</th>
        <th>Avg Time / Call</th>
      </thead>
      <% employee_performance(@employee) %>
      <tr class="values">
        <td><%= @call_count %></td>
        <td><%= @success_percentage %>%</td>
        <td><%= @calls_per_day %></td>
        <td>~<%= @average_call_duration %></td>
      </tr>
      

      <tr class="comparison">
        <td><%= employee_call_count_comparison(@employee) %></td>
        <td><%= employee_success_comparison(@employee) %></td>
        <td><%= employee_avg_calls_comparison(@employee) %></td>
        <td><%= employee_avg_time_comparison(@employee) %></td>
      </tr>

    </table>

  </section>
</div>


<div class="row">
<section class="twelve columns container" id="employee-call-data">
    <header class="emp-performance-header">
       Call History
    </header>
    <table class="general-table">
    <thead>
      <th>Date</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Call Wait Period (Secs)</th>
      <th>Call Duration (Mins)</th>
    </thead>
  <% @calls_report.each do |call| %>
    <tr>
      <td><%= call.call_starttime.strftime("%d %b,%Y") %></td>
      <td><%= call.call_starttime.strftime("%I:%M%p") %></td>
      <td><%= call.call_endTime.strftime("%I:%M%p") %></td>
      <td><%= call.call_wait_period %>  (approx. <%= convert_to_mins(call.call_wait_period) +1 %>mins)</td>
      <td><%= convert_to_mins(call.call_duration) %></td>
    </tr>
  <% end %>
  </table>
</section><!-- /Employee Call Data -->
</div>

app/views/employees/sick.html.erb
<section  class="twelve columns container">

<header class="main-page-header">Employees on Sick Leave ( <%= current_user_employees.where(:employee_status_id => 4).count %> )
<span class="import-button"><%= link_to "Allocate", new_employee_path %></span>
</header>

<table class="general-table">
  <thead>
    <tr>
      <th>Employee Id</th>
      <th>Full Name</th>
      <th>Commenced Work</th>
      <th>Contact Number</th>
      <th>Email Address</th>
      <th>Current Status</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td>DD_<%= employee.id %></td>
        <td><%= link_to employee.full_name_rev.upcase, employee, :class => "employee-name" %></td>
        <td><%= employee.employee_started %></td>
        <td><%= employee.employee_contact_num %></td>
        <td><%= employee.employee_email %></td>
        <td><%= EmployeeStatus.find(employee.employee_status_id).es_type.capitalize %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</section>