config/routes.rb
Dd::Application.routes.draw do

  
  resources :password_resets
  resources :skills
  resources :users
  resources :session, only: [:new, :create, :destroy]
  resources :dashboard
  resources :settings
  resources :employees do
    collection { post :import }
  end
  resources :calls do
    collection { post :import }
  end
  resources "contacts", only: [:new, :create]
  resources "requests", only: [:new, :create]

    root 'session#new'
    get 'signin', to: "session#new"
    match 'signout', to: "session#destroy", via: :delete
    get 'administration', to: "admin_users#index", as: "administration"
    get 'employee_import', to: "employees#employee_import"
    get 'employee_active', to: "employees#active"
    get 'employee_leave', to: "employees#leave"
    get 'employee_sick', to: "employees#sick"
    get 'employee_maternity', to: "employees#maternity"
    get 'employee_compassionate', to: "employees#compassionate"
    get 'employee_retrenched', to: "employees#retrenched"
    get 'employee_active_allocate', to: "employees#active_allocate"
    match '/contacts', to: 'contacts#new', via: 'get'
    match '/requests', to: 'requests#new', via: 'get'
    get "active/new"
    

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	include SessionHelper
  include ApplicationHelper

	def new

    if signed_in?
      if current_user.role_id == 2
        flash[:notice] = "Already signed in"
        redirect_to dashboard_index_path
      elsif current_user.role_id== 1
        flash[:notice] = "Already signed in"
        redirect_to admin_users_path 
      end        
    end

  end

  def create
  	user = User.find_by_user_email(params[:session][:email].downcase)
  	@user = user

    if user && user.authenticate(params[:session][:password])
		if params[:remember_me]  
			cookies.permanent[:auth_token] = user.auth_token  
		else  
			cookies[:auth_token] = user.auth_token    
		end 
		
		user.increment_login
		
		sign_in user
        

        #User Type determines which interface to load
        if current_user.role_id == 2
      	  redirect_to dashboard_index_path
        elsif current_user.role_id == 1
          redirect_to administration_path
        end
    else
      	flash[:error] = 'Incorrect Email/Password Combination'
      	redirect_to signin_path    
    end
  end

  def destroy
    #Before destroy, save user name for logging out message
    leaving_user = current_user.user_fname.capitalize + " " + current_user.user_lname.capitalize

	cookies.delete(:auth_token) 
	
    sign_out
    flash[:success] = "#{leaving_user} logged out successfully"
    redirect_to signin_path
  end
end

app/helpers/session_helper.rb
module SessionHelper
	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		self.current_user = user
	end

	def current_user=(user)
		@current_user = user	
	end

	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end

	def signed_in?
		!current_user.nil?	
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end
end

app/views/session/new.html.erb
<!-- Message to the User -->
<% flash.each do |key, value| %>
  <div class="flash session-flash alert alert-<%= key %>"><%= h(value) %></div>
<% end %>

<section id="login" class="row">
<!-- Group Logo -->
<header>
	<%= link_to image_tag("favicon3.png"), root_path, :title => "Dimension Data WFMS" %>
	<p>WFMS Sign In</p>
</header>

<!-- Form for user login -->
<%= form_for(:session, url: session_index_path) do |f| %>

  <ul id="login-fields">   
    <li>
      <span class="adjoined"><i class="fa fa-user"></i></span>
      <%= f.text_field :email, :placeholder => "Email Address" %>
    </li>

    <li>
      <span class="adjoined"><i class="fa fa-unlock"></i></span>
      <%= f.password_field :password, :placeholder => "Password" %> <br />
    </li> 
	
  </ul>

  <p id="remember">
		<%= check_box_tag :remember_me, 1, params[:remember_me] %> 
		<%= label_tag :keep_me_logged_in %>
  </p>  
  
  <%= f.submit "Login" %>
 
<% end %>
<!-- Link to retrieve lost password -->
<p id="forgot-password"><%= link_to 'Forgotten Password', new_password_reset_path %> | 
<%= link_to 'Contact Administrator', contacts_path %> | 
<%= link_to 'Request Account', requests_path %></p>

</section><!-- /user-login -->