config/routes.rb
Dd::Application.routes.draw do

  
  resources :password_resets
  resources :skills
  resources :users
  resources :session, only: [:new, :create, :destroy]
  resources :dashboard
  resources :settings
  resources :employees do
    collection { post :import }
  end
  resources :calls do
    collection { post :import }
  end
  resources "contacts", only: [:new, :create]
  resources "requests", only: [:new, :create]

    root 'session#new'
    get 'signin', to: "session#new"
    match 'signout', to: "session#destroy", via: :delete
    get 'administration', to: "admin_users#index", as: "administration"
    get 'employee_import', to: "employees#employee_import"
    get 'employee_active', to: "employees#active"
    get 'employee_leave', to: "employees#leave"
    get 'employee_sick', to: "employees#sick"
    get 'employee_maternity', to: "employees#maternity"
    get 'employee_compassionate', to: "employees#compassionate"
    get 'employee_retrenched', to: "employees#retrenched"
    get 'employee_active_allocate', to: "employees#active_allocate"
    match '/contacts', to: 'contacts#new', via: 'get'
    match '/requests', to: 'requests#new', via: 'get'
    get "active/new"
    

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	#include SessionHelper

	def index

		if signed_in?
			if current_user.role_id == 2
				redirect_to dashboard_index_path
			elsif current_user.role_id == 2
				redirect_to administration_path
			end
		end

	end
	
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<section class="row container" id="welcome-section">
	<!-- Error Message to the User -->
	<% flash.each do |key, value| %>
	  <div class="flash alert alert-<%= key %>"><%= h(value) %></div>
	<% end %>
	<header>Workforce Managment System</header>

<p>
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vitae imperdiet felis. Pellentesque eleifend pretium interdum. Sed vel feugiat neque. Nullam ac diam non tellus pellentesque porttitor. Sed dignissim dolor ipsum, et scelerisque justo tristique id. Sed pulvinar ante quis ipsum iaculis posuere. Cras quis metus risus. Aliquam sed cursus est, eget interdum lorem. Morbi vitae ipsum sit amet tortor suscipit viverra. Fusce tincidunt nisi tortor, a dignissim tortor convallis non. Duis tempus elementum lacus vel commodo. Vestibulum vel tempor diam. In ligula erat, tincidunt auctor felis ac, luctus dapibus est. Donec faucibus varius tortor at aliquet. Donec ligula nisi, facilisis nec risus non, aliquet accumsan leo.
</p>
	
	<%= link_to "Enter The System", signin_path %>
</section><!-- /welcome_section -->